WebUI/Controllers/DocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DomainModel.Entity;
using DomainModel;
using System.Web.Http;
using System.Net;
using System.Net.Http;
using System.IO;

namespace WebUI.Controllers
{
    public class DocController : Controller
    {
        //
        // GET: /Doc/

        public RedirectResult Index()
        {
            return RedirectPermanent("/Home/Index");
        }


        public ActionResult About(int id)
        {
            try
            {
                DocInformation dInfo = new DocInformation();
                Document document = dInfo.GetDocInfo(id);
                return View(document);
            }
            catch (Exception ex)
            {
                return View("DisplayError", ex);
            }
        }

        
        public ActionResult DownloadFile(int id)
        {
            try
            {
                DownloadedFile downloadedFile = new DownloadedFile();
                downloadedFile.Download(id);

                return File(downloadedFile.FileContent, downloadedFile.FileType, downloadedFile.FileName);
            }
            catch (Exception ex)
            {
                return View("DisplayError", ex);
            }
        }


        public ActionResult GetPDF(int id)
        {
            try
            {
                DownloadedFile downloadedFile = new DownloadedFile();
                downloadedFile.Download(id);

                Response.AppendHeader("Content-Disposition", "inline; filename=" + downloadedFile.FileName);
                return File(downloadedFile.FileContent, downloadedFile.FileType);
            }
            catch (Exception ex)
            {
                return View("DisplayError", ex);
            }
        }

    }
}

WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Добро пожаловать";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

WebUI/Controllers/SearchController.cs
using DomainModel.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class SearchController : Controller
    {
        //
        // GET: /Search/

        public RedirectResult Index()
        {
            return RedirectPermanent("/Search/Simple");
        }

        [System.Web.Mvc.HttpGet]
        public ActionResult Simple()
        {
            return View();
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult Simple(String q)
        {
            DocSearch docSearch = new DocSearch();
            ViewBag.q = q;
             
            try
            {
                docSearch.SimpleSearch(q);
                ViewBag.ResultCount = docSearch.CountResults;
                return View("Results", docSearch.Results.ToList());
            }
            catch (Exception ex)
            {
                ViewBag.ExMsg = "Результаты поиска";
                return View("DisplayError", ex);
            }
        }



        [System.Web.Mvc.HttpGet]
        public ActionResult FullText()
        {
            return View();
        } 

        
        [System.Web.Mvc.HttpPost]
        public ActionResult FullText(String q)
        {
            DocSearch docSearch = new DocSearch();
            ViewBag.q = q;

            try
            {
                docSearch.FullTextSearch(q);
                ViewBag.ResultCount = docSearch.CountResults;
                return View("Results", docSearch.Results.ToList());
            }
            catch (Exception ex)
            {
                ViewBag.ExMsg = "Результаты поиска";
                return View("DisplayError", ex);
            }
        }


        public ActionResult CatalogByAuthor()
        {
            return View();
        }


        public ActionResult CatalogByAuthorResponse(String letter)
        {
            DocSearch docSearch = new DocSearch();
            ViewBag.q = letter;
            try
            {
                docSearch.SearchByLetter(letter, false);
                ViewBag.ResultCount = docSearch.CountResults;
                return View("Results", docSearch.Results.ToList());
            }
            catch (Exception ex)
            {
                ViewBag.ExMsg = "Результаты поиска";
                return View("DisplayError", ex);
            }
        }


        public ActionResult CatalogByTitle()
        {
            return View();
        }


        public ActionResult CatalogByTitleResponse(String letter)
        {
            DocSearch docSearch = new DocSearch();
            ViewBag.q = letter;
            try
            {
                docSearch.SearchByLetter(letter, true);
                ViewBag.ResultCount = docSearch.CountResults;
                return View("Results", docSearch.Results.ToList());
            }
            catch (Exception ex)
            {
                ViewBag.ExMsg = "Результаты поиска";
                return View("DisplayError", ex);
            }
        } 

    }
}

WebUI/Views/Doc/About.cshtml
@model DomainModel.Entity.Document

@{
    ViewBag.Title = @Model.ShortTitle;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Description {
    @if (!@Model.Annotation.Equals("Отсутствует")){
    <meta name="description" content="@Model.Annotation"/>
    }else{<meta name="description" content="@Model.Keywords"/>}
}
@section Keywords {
    <meta name="keywords" content="@Model.Keywords" />
}
@section Author {
    <meta name="author" content="@Model.Author"/>
}

<h2>Дополнительная информация о документе</h2>

<fieldset>
    <legend>
        "@Model.FullTitle"
    </legend>

    <dl class="dl-horizontal">

        <dt>Полное название</dt>
        <dd>@Html.DisplayFor(model => model.FullTitle)</dd>


        <dt>Авторы</dt>
        <dd>@Html.DisplayFor(model => model.Author)</dd>


        <dt>Дата создания</dt>
        <dd>@Html.DisplayFor(model => model.CreateDate)</dd>


        <dt>Размер файла</dt>
        <dd>@Html.DisplayFor(model => model.FileSize) байт</dd>


        <dt>Расширение</dt>
        <dd>@Html.DisplayFor(model => model.Extension)</dd>

        
        <dt>Формат документа</dt>
        <dd>@Html.DisplayFor(model => model.Format)</dd>

        <dt>Аннотация</dt>
        <dd>@Html.DisplayFor(model => model.Annotation)</dd>


       
         <!-- Правка названий -->

        <dt>Ключевые слова</dt>
        <dd>@Html.DisplayFor(model => model.Keywords)</dd>


        <dt>Соавторы</dt>
        <dd>@Html.DisplayFor(model => model.CoAuthor)</dd>

    </dl>
    <div class="form-actions">
        @Html.ActionLink("Скачать", "DownloadFile", "Doc", new { id = Model.ID },
                new { @class = "btn btn-primary" })
        @Html.ActionLink("Просмотр", "GetPDF", "Doc", new { id = Model.ID },
                new { @class = "btn btn-primary" })
        <button type="button" class="btn" onclick="history.back()">Назад</button>
    </div>
</fieldset>

WebUI/Views/Doc/AdvancedSearch.cshtml
@model IEnumerable<DomainModel.Entity.Document>

@{
    ViewBag.Title = "AdvancedSearch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AdvancedSearch</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class = "table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Extension)
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Extension)
        </td>
        <td>
            @Html.ActionLink("Download", "DownloadFile", "Doc", new { id=item.ID }, null) <br />
            @Html.ActionLink("Details", "About", "Doc", new { id=item.ID }, null) 
        </td>
    </tr>
}

</table>

WebUI/Views/Doc/Author.cshtml
@{
    ViewBag.Title = "Каталог по авторам";

    String strEn = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    String strRus = "АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЭЮЯ";        
}

<h2>@ViewBag.Title</h2>

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">A-Z</a></li>
    <li><a href="#tab2" data-toggle="tab">А-Я</a></li>
  </ul>
  <div class="tab-content">
      <div class="tab-pane active" id="tab1">

          <div class="btn-group">
              @for (int i = 0; i < strEn.Length; i++)
              {
              
                  @Html.ActionLink(strEn[i].ToString(), "TitleSearch", "Doc",
                                                new { q = strEn[i].ToString(), inTitle = false },
                                                new { @class = "btn" })
                 if (i == strEn.Length / 2)
                 {<br />}
             }
          </div>

      </div>
    <div class="tab-pane" id="tab2">
      <div class="btn-group">
              @for (int i = 0; i < strRus.Length; i++)
              {
              
                  @Html.ActionLink(strRus[i].ToString(), "TitleSearch", "Doc",
                                                new { q = strRus[i].ToString(), inTitle = false }, 
                                                new { @class = "btn" })
                 if (i == strRus.Length / 2)
                 {<br />}
             }
          </div>
    </div>
  </div>
</div>

WebUI/Views/Doc/DownloadFile.cshtml
@model DomainModel.Entity.Document

@{
    ViewBag.Title = "DownloadFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DownloadFile</h2>

<fieldset>
    <legend>Document</legend>

    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>
           

        <dt>@Html.DisplayNameFor(model => model.Title)</dt>
        <dd>@Html.DisplayFor(model => model.Title)</dd>


        <dt> @Html.DisplayNameFor(model => model.Type)</dt>
        <dd> @Html.DisplayFor(model => model.Type)</dd>


        <dt>@Html.DisplayNameFor(model => model.Author)</dt>
        <dd>@Html.DisplayFor(model => model.Author)</dd>


        <dt> @Html.DisplayNameFor(model => model.CreateDate)</dt>
        <dd>@Html.DisplayFor(model => model.CreateDate)</dd>


        <dt>@Html.DisplayNameFor(model => model.FileSize)</dt>
        <dd>@Html.DisplayFor(model => model.FileSize)</dd>


        <dt>@Html.DisplayNameFor(model => model.Extension)</dt>
        <dd>@Html.DisplayFor(model => model.Extension)</dd>


        <dt>@Html.DisplayNameFor(model => model.Format)</dt>
        <dd>@Html.DisplayFor(model => model.Format)</dd>

        <dd>
            @Html.ActionLink("Скачать", "DownloadFile", "Doc", new { id = Model.ID },
                new { @class = "pull-right btn btn-primary" })
        </dd>

    </dl>
        
</fieldset>

WebUI/Views/Doc/LetterSearch.cshtml
@model IEnumerable<DomainModel.Entity.Document>

@{
    ViewBag.Title = "Результаты поиска";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="text-center">Форма для поиска</h3>
<div class="row-fluid">
    <div class="span5 offset3">
        
        <form method="post" action="/Doc/FormSearch">
            <div class="input-append span12">
                <input type="text" class="input-block-level" id="focusedInput" name="q" placeholder=@ViewBag.q>
                <button type="submit" class="btn">Найти</button>
            </div>
        </form>
    </div>
</div>

<h3 class="text-center">Результаты поиска</h3>


<table class="table table-bordered table-hover">
    <tr>
        <th>
            Заголовок
        </th>
        <th>
            Автор
        </th>
        <th>
            Разрешение
        </th>
        <th>
            Дата создания
        </th>
        <th>Действия</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Extension)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.ActionLink("Скачать", "DownloadFile", "Doc", new { id = item.ID }, null) <br /> 
                    @Html.ActionLink("Подробнее", "About", "Doc", new { id = item.ID }, null)
                </td>
            </tr>
        }
    </tbody>
</table>

WebUI/Views/Doc/QuickSearch.cshtml
@{
    ViewBag.Title = "Поиск";
}

<h2>Поиск</h2>

<div class="row-fluid">
    <div class="span5 offset3">
        <form method="post" action="/Doc/FormSearch">
            <div class="input-append span12">
                <input type="text" class="input-block-level" name="q">
                <button type="submit" class="btn">Найти</button>
            </div>
        </form>
    </div>
</div>

@{Html.RenderPartial("SearchResults");}

WebUI/Views/Doc/Search.cshtml
@{
    ViewBag.Title = "Поиск";
}

<h2>Поиск</h2>

<div class="row-fluid">
    <div class="span5 offset3">
        <form method="post" action="/Doc/FormSearch">
            <div class="input-append span12">
                <input type="text" class="input-block-level" name="q">
                <button type="submit" class="btn">Найти</button>
            </div>
        </form>
    </div>
</div>

WebUI/Views/Doc/SearchForm.cshtml
@{
    ViewBag.Title = "SearchForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SearchForm</h2>
<form action="/Doc/AdvancedSearch" method="post" class="">
    <input name="" class="input-xxlarge" id="appendedInputButton" type="text"/>
    <input class="btn btn-primary" type="submit" value="Search" />

</form>

WebUI/Views/Doc/SearchResult.cshtml
@model IEnumerable<DomainModel.Entity.Document>

@{
    ViewBag.Title = "Результаты поиска";
    Layout = "~/Views/Shared/_Layout.cshtml";

    String strEn = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    String strRus = "АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЭЮЯ";  
}

@if (ViewBag.inTitle) { <h2>Каталог по названиям</h2> }
else { <h2>Каталог по авторам</h2> }


<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">A-Z</a></li>
    <li><a href="#tab2" data-toggle="tab">А-Я</a></li>
  </ul>
  <div class="tab-content">
      <div class="tab-pane active" id="tab1">

          <div class="btn-group">
              @for (int i = 0; i < strEn.Length; i++)
              {
                  if (ViewBag.inTitle)
                  {
                    @Html.ActionLink(strEn[i].ToString(), "TitleSearch", "Doc",
                                                new { q = strEn[i].ToString(), inTitle = true }, 
                                                new { @class = "btn" })
                  }
                  else
                  {
                    @Html.ActionLink(strEn[i].ToString(), "TitleSearch", "Doc",
                                                new { q = strEn[i].ToString(), inTitle = false }, 
                                                new { @class = "btn" })    
                  }
                  
                 if (i == strEn.Length / 2)
                 {<br />}
             }
          </div>

      </div>
    <div class="tab-pane" id="tab2">
      <div class="btn-group">
              @for (int i = 0; i < strRus.Length; i++)
              {
                 if (ViewBag.inTitle)
                 {
                    @Html.ActionLink(strRus[i].ToString(), "TitleSearch", "Doc",
                                                new { q = strRus[i].ToString(), inTitle = true }, new { @class = "btn" })
                  }
                  else
                  {
                     @Html.ActionLink(strRus[i].ToString(), "TitleSearch", "Doc",
                                                new { q = strRus[i].ToString(), inTitle = false }, new { @class = "btn" })
                  }
                 if (i == strRus.Length / 2)
                 {<br />}
             }
          </div>
    </div>
  </div>
</div>

@{Html.RenderPartial("SearchResults");}

WebUI/Views/Doc/Title.cshtml
@{
    ViewBag.Title = "Каталог по названиям";

    String strEn = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    String strRus = "АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЭЮЯ";        
}

<h2>@ViewBag.Title</h2>

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">A-Z</a></li>
    <li><a href="#tab2" data-toggle="tab">А-Я</a></li>
  </ul>
  <div class="tab-content">
      <div class="tab-pane active" id="tab1">

          <div class="btn-group">
              @for (int i = 0; i < strEn.Length; i++)
              {
              
                  @Html.ActionLink(strEn[i].ToString(), "TitleSearch", "Doc",
                                                new { q = strEn[i].ToString(), inTitle = true },
                                                new { @class = "btn" })
                 if (i == strEn.Length / 2)
                 {<br />}
             }
          </div>

      </div>
    <div class="tab-pane" id="tab2">
      <div class="btn-group">
              @for (int i = 0; i < strRus.Length; i++)
              {
              
                  @Html.ActionLink(strRus[i].ToString(), "TitleSearch", "Doc",
                                                new { q = strRus[i].ToString(), inTitle = true }, 
                                                new { @class = "btn" })
                 if (i == strRus.Length / 2)
                 {<br />}
             }
          </div>
    </div>
  </div>
</div>

WebUI/Views/Doc/ViewMeta.cshtml
@model DomainModel.MetaDataRef.DocTypes

@{
    ViewBag.Title = "ViewMeta";
}

<h2>ViewMeta</h2>

<fieldset>
    <legend>DocTypes</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dDocType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dDocType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dGif)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dGif)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "О ресурсе · Каталоги ТПУ";
}

<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <div class="span7">
                <hgroup class="title">
                    <h1>О ресурсе</h1>
                    <h2>Каталоги ТПУ</h2>
                </hgroup>
                <article>
                    <p>
                        Данный сервис является результатом выпускной квалификационной работы на соискание степени бакалавра и запущен в тестовом режиме. В ближайшем времени планируется отладка приложения
                        и расширение базового функционала. Разработано студентом А.В. Распоповым под руководством к.т.н. В.С. Шерстнева.
                    </p>
                    <p>
                        Ресурс предоставляет редкий и уникальный исследовательский материал, 
                        состоящий  из объединенных в каталог более 5000 научных документов. В базе данных вы можете обнаружить 
                        запасы научной технической библиотеки Томского политехнического университета​​. Сотрудники и студенты ТПУ 
                        используют этот ресурс для того, чтобы быстро и легко найти необходимые учебные материалы и 
                        проверить информацию о документах. 
                    </p>
                    <p>
                        Функция поиска означает, что вы ищете широкую и разнообразную коллекцию документов 
                        Томского политехнического университета. Поиск осуществляется через взаимодействие приложения
                        с Oracle Universal Content Management System, и происходит по содержимому сервера контента. 
                        Также ресурс предлагает возможность поиска внутри документов - полнотекстовый поиск. 
                        Функция полнотекстового поиска обладает исключительной возможностью поиска 
                        по содержимому документов.
                    </p>
                </article>
            </div>
            <div class="span5">
                <aside class="pull-right">
                    <h3>Меню</h3>
                    <p>
                        Вы можете пройти по следующим ссылкам:
                    </p>
                    <ul>
                        <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                        <li>@Html.ActionLink("Простой поиск", "Simple", "Search")</li>
                        <li>@Html.ActionLink("Полнотекстовый поиск", "FullText", "Search")</li>
                        <li>@Html.ActionLink("Каталог по авторам", "CatalogByAuthor", "Search")</li>
                        <li>@Html.ActionLink("Каталог по названиям", "CatalogByTitle", "Search")</li>
                        <li>@Html.ActionLink("О ресурсе", "About", "Home")</li>
                        <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                    </ul>
                </aside>

            </div>
        </div>
    </div>
</div>
    

WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакты · Каталоги ТПУ";
}

<hgroup class="title">
    <h1>Контактная информация</h1>
    <h2>Каталоги ТПУ</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Телефон</h3>
    </header>
    <p>
        <span class="label">Основной:</span>
        <span>(1234) - 123-123</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Факс</h3>
    </header>
    <p>
        <span class="label">Основной:</span>
        <span>(1234) - 123-123</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Адрес электронной почты</h3>
    </header>
    <p>
        <span class="label">Поддержка:</span>
        <span><a href="mailto:vt@vt.tpu.ru">vt@vt.tpu.ru</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Адрес</h3>
    </header>
    <p>
        <span class="label">Главный корпус:</span>
        <span>634050, г. Томск, пр. Ленина, 30, офис 127</span>
    </p>
    <p>
        <span class="label">Кафедра ВТ Института Кибернетики:</span>
        <span>634034, г. Томск, пр. Ленина, 2, Учебный корпус №10, офис 404</span>
    </p>
</section>

WebUI/Views/Search/CatalogByAuthor.cshtml
@{
    ViewBag.Title = "Каталог по авторам";

    String strEn = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    String strRus = "АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЭЮЯ"; 
}

<h2>@ViewBag.Title</h2>
<div class="well well-small">
    <div class="pagination pagination-small">
        <ul>
            @for (int i = 0; i < strRus.Length; i++)
            {              
                <li>
                @Html.ActionLink(strRus[i].ToString(), "CatalogByAuthorResponse", "Search", new { letter = strRus[i].ToString() }, new { @class = "btn" })
                </li>
            }
        </ul>
    </div>
    <div class="pagination pagination-small">
        <ul>
            @for (int i = 0; i < strEn.Length; i++)
            {              
                <li>
                @Html.ActionLink(strEn[i].ToString(), "CatalogByAuthorResponse", "Search", new { letter = strEn[i].ToString() }, new { @class = "btn" })
                </li>
            }
        </ul>
    </div>
</div>

WebUI/Views/Search/CatalogByTitle.cshtml
@{
    ViewBag.Title = "Каталог по названиям";

    String strEn = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    String strRus = "АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЭЮЯ"; 
}

<h2>@ViewBag.Title</h2>
<div class="well well-small">
    <div class="pagination pagination-small">
        <ul>
            @for (int i = 0; i < strRus.Length; i++)
            {              
                <li>
                @Html.ActionLink(strRus[i].ToString(), "CatalogByTitleResponse", "Search", new { letter = strRus[i].ToString() }, new { @class = "btn" })
                </li>
            }
        </ul>
    </div>
    <div class="pagination pagination-small">
        <ul>
            @for (int i = 0; i < strEn.Length; i++)
            {              
                <li>
                @Html.ActionLink(strEn[i].ToString(), "CatalogByTitleResponse", "Search", new { letter = strEn[i].ToString() }, new { @class = "btn" })
                </li>
            }
        </ul>
    </div>
</div>

WebUI/Views/Search/Results.cshtml
@model IEnumerable<DomainModel.Entity.Document>

@{
    ViewBag.Title = "Результаты поиска - \"" +@ViewBag.q+"\"";
}

<h2>@ViewBag.Title <button type="button" class="btn btn-primary" onclick="history.back()">Назад</button></h2>
<h4>Найдено документов - @ViewBag.ResultCount</h4>

<table class="table table-bordered table-hover">
    <tr>
        <th>
            <abbr title="Вы можете ознакомиться с подробной информацией о конкретном документе, щелкнув по его заголовку в этой колонке">Название</abbr><i class="icon-info-sign"></i>
        </th>
        <th>
            Авторы
        </th>
        <th>
            <abbr title="Вы можете скачать конкретный документ, щелкнув на его расширении в этой колонке">Расширение</abbr><i class="icon-info-sign"></i>
        </th>
        <th>
            Дата создания
        </th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.ShortTitle, "About", "Doc", new { id = item.ID }, null)
                    @*<a href="/Doc/About/@item.ID">@item.ShortTitle</a>*@
                </td>
                <td class="align-center">
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td class="align-center">
                    @Html.ActionLink(item.Extension, "DownloadFile", "Doc", new { id = item.ID }, null)
                </td>
                <td class="align-center">
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>

            </tr>
        }
    </tbody>
</table>

WebUI/Views/Shared/SearchResults.cshtml
@model IEnumerable<DomainModel.Entity.Document>

<h2 class="text-left">Результаты поиска</h2>

<table class="table table-bordered table-hover">
    <tr>
        <th>
            Название
        </th>
        <th>
            Авторы
        </th>
        <th>
            Расширение
        </th>
        <th>
            Дата создания
        </th>
        <th>Действия</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ShortTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Extension)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.ActionLink("Скачать", "DownloadFile", "Doc", new { id = item.ID }, null) <br /> 
                    @Html.ActionLink("Подробнее", "About", "Doc", new { id = item.ID }, null)
                </td>
            </tr>
        }
    </tbody>
</table>